name: Build, sign, and push container image

on:
  push:
    branches:
      - main

jobs:
  build-sign-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.email "kulkarni_pp@rediffmail.com"
          git config --global user.name "kulkarnipp78"
        env:
          CI: true

      - name: azure login
        run: |
          az login --use-device-code

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

     
      - name: maven install
        run:
          mvn clean package

      - name: Build the image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/insurancemanager:1 .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/insurancemanager:1
            
      - name: doxygen-install
        # You may pin to the exact commit or the version.
        # uses: ssciwr/doxygen-install@d03a7fc93d72531344b2cb7d5784c616373371a6
        uses: ssciwr/doxygen-install@v1.3.0
        with:
          # The Doxygen version to install
          version: 1.10.0

      - name: Doxygen Action
      # You may pin to the exact commit or the version.
      # uses: mattnotmitt/doxygen-action@cbe72c8e402e8a3faa1f0b247ef90aa6c8e4ce74
        uses: mattnotmitt/doxygen-action@1.9.8
        with:
          # Path to Doxyfile
          doxyfile-path: ./Documentation/Doxyfile
          # Working directory
          working-directory: ./WebAppDemo
          # Generate latex documentation
          enable-latex: True
